# Generated by Django 5.0.3 on 2024-05-08 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="FoodRecipes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoryCD",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("food_recipe", "음식 레시피"),
                            ("broadcast_recipe", "방송 레시피"),
                            ("convenience_store_combination", "편의점 꿀 조합"),
                            ("seasoning_recipe", "양념 레시피"),
                            ("cooking_tip", "요리 TIP"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("tot_price", models.IntegerField(blank=True, null=True)),
                (
                    "thumnail",
                    models.ImageField(blank=True, null=True, upload_to=core.functions.upload_thumnail_directory),
                ),
                ("video", models.URLField(blank=True, null=True)),
                ("intro", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("people_num", models.IntegerField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("easy", "쉬움"), ("medium", "보통"), ("hard", "어려움")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "bookmark",
                    models.ManyToManyField(
                        blank=True, related_name="user_foodrecipe_bookmark", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True, related_name="user_foodrecipe_like", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_foodrecipe_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ConvenienceItems",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                (
                    "foodrecipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convenience_items",
                        to="recipes.foodrecipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("count", models.SmallIntegerField()),
                ("unit", models.CharField(max_length=10)),
                ("etc", models.CharField(max_length=255)),
                (
                    "foodrecipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.foodrecipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=core.functions.upload_user_directory)),
                ("state", models.CharField(choices=[("임시저장", "임시저장"), ("반영", "반영")], default="임시저장", max_length=10)),
                (
                    "foodrecipe",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_image",
                        to="recipes.foodrecipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeProcess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                (
                    "foodrecipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_process",
                        to="recipes.foodrecipes",
                    ),
                ),
            ],
        ),
    ]
