# Generated by Django 5.0.3 on 2024-06-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.functions


class Migration(migrations.Migration):

    dependencies = [("recipes", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.AddField(
            model_name="recipeimage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_image",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipeprocess",
            name="image",
            field=models.ImageField(default="default1", upload_to=core.functions.upload_process_image_directory),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="foodrecipes", name="thumnail", field=models.ImageField(blank=True, null=True, upload_to="")
        ),
        migrations.AlterField(
            model_name="recipeimage",
            name="foodrecipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_image",
                to="recipes.foodrecipes",
            ),
        ),
        migrations.AlterField(
            model_name="recipeimage",
            name="image",
            field=models.ImageField(upload_to=core.functions.upload_image_directory),
        ),
    ]
