# Generated by Django 5.0.3 on 2024-06-27 09:05

from django.db import migrations, models

import core.functions


class Migration(migrations.Migration):

    dependencies = [("recipes", "0002_recipeimage_user_recipeprocess_image_and_more")]

    operations = [
        migrations.AlterField(
            model_name="foodrecipes",
            name="thumnail",
            field=models.ImageField(default="default", upload_to=core.functions.upload_image_directory),
            preserve_default=False,
        )
    ]
