# Generated by Django 5.0.3 on 2024-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0003_alter_foodrecipes_thumnail")]

    operations = [
        migrations.AddField(
            model_name="recipeprocess", name="order", field=models.SmallIntegerField(default=1), preserve_default=False
        )
    ]
